#!/bin/bash
# generate_templates.sh - Auto-generate templates.c from templates/ directory

set -e

TEMPLATE_DIR="templates"
OUTPUT_FILE="src/templates.c"

echo "Generating templates.c from templates/ directory..."

# Check if templates directory exists
if [ ! -d "$TEMPLATE_DIR" ]; then
    echo "Error: templates/ directory not found!"
    exit 1
fi

# Count templates
TEMPLATE_COUNT=$(find "$TEMPLATE_DIR" -name "*.gitignore" | wc -l)
if [ "$TEMPLATE_COUNT" -eq 0 ]; then
    echo "Error: No .gitignore files found in templates/"
    exit 1
fi

echo "Found $TEMPLATE_COUNT template(s)"

# Start generating templates.c
cat > "$OUTPUT_FILE" << 'HEADER'
// templates.c - Auto-generated built-in templates
// DO NOT EDIT MANUALLY - Generated by scripts/generate_templates.sh

#include "gitignore.h"

// Built-in template structure
typedef struct {
    const char *name;
    const char *content;
} builtin_template_t;

HEADER

# Generate template variables
for template_file in "$TEMPLATE_DIR"/*.gitignore; do
    if [ -f "$template_file" ]; then
        # Extract name (remove path and .gitignore extension)
        template_name=$(basename "$template_file" .gitignore)
        
        echo "  Processing: $template_name"
        
        # Generate C string variable
        echo "// $template_name template" >> "$OUTPUT_FILE"
        echo "static const char ${template_name}_template[] = " >> "$OUTPUT_FILE"
        
        # Read file line by line and convert to C string
        while IFS= read -r line || [ -n "$line" ]; do
            # Escape special characters
            escaped_line=$(echo "$line" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')
            echo "\"$escaped_line\\n\"" >> "$OUTPUT_FILE"
        done < "$template_file"
        
        echo ";" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
    fi
done

# Generate template array
cat >> "$OUTPUT_FILE" << 'ARRAY_START'
// All built-in templates
static const builtin_template_t builtin_templates[] = {
ARRAY_START

# Add entries to array
for template_file in "$TEMPLATE_DIR"/*.gitignore; do
    if [ -f "$template_file" ]; then
        template_name=$(basename "$template_file" .gitignore)
        echo "    {\"$template_name\", ${template_name}_template}," >> "$OUTPUT_FILE"
    fi
done

cat >> "$OUTPUT_FILE" << 'ARRAY_END'
    {NULL, NULL}
};

// Get built-in template by name
const char* get_builtin_template(const char *name) {
    for (int i = 0; builtin_templates[i].name != NULL; i++) {
        if (strcasecmp(builtin_templates[i].name, name) == 0) {
            return builtin_templates[i].content;
        }
    }
    return NULL;
}

// Check if template is built-in
int is_builtin_template(const char *name) {
    return get_builtin_template(name) != NULL;
}

// Get all built-in template names
const char** get_builtin_template_names(void) {
    static const char *names[64];
    int count = 0;
    
    for (int i = 0; builtin_templates[i].name != NULL && count < 63; i++) {
        names[count++] = builtin_templates[i].name;
    }
    names[count] = NULL;
    
    return names;
}
ARRAY_END

echo "✓ Generated $OUTPUT_FILE with $TEMPLATE_COUNT templates"
echo "✓ Templates: $(find "$TEMPLATE_DIR" -name "*.gitignore" -exec basename {} .gitignore \; | tr '\n' ' ')"