// templates.c - Auto-generated built-in templates
// DO NOT EDIT MANUALLY - Generated by scripts/generate_templates.sh

#include "gitignore.h"

// Built-in template structure
typedef struct {
    const char *name;
    const char *content;
} builtin_template_t;

// c template
static const char c_template[] = 
"# C\n"
"*.o\n"
"*.a\n"
"*.so\n"
"*.out\n"
"*.exe\n"
"*.dylib\n"
;

// cpp template
static const char cpp_template[] = 
"# C++\n"
"*.o\n"
"*.obj\n"
"*.exe\n"
"*.out\n"
"*.a\n"
"*.so\n"
"*.dylib\n"
;

// go template
static const char go_template[] = 
"# Go\n"
"*.exe\n"
"*.test\n"
"*.out\n"
"vendor/\n"
;

// java template
static const char java_template[] = 
"# Java\n"
"*.class\n"
"*.jar\n"
"*.war\n"
"*.ear\n"
"target/\n"
".gradle/\n"
"build/\n"
;

// linux template
static const char linux_template[] = 
"# Linux\n"
"*~\n"
".directory\n"
;

// macos template
static const char macos_template[] = 
"# macOS\n"
".DS_Store\n"
".AppleDouble\n"
".LSOverride\n"
;

// node template
static const char node_template[] = 
"# Node.js\n"
"node_modules/\n"
"npm-debug.log*\n"
"yarn-debug.log*\n"
"yarn-error.log*\n"
".npm\n"
"dist/\n"
"build/\n"
".next/\n"
".nuxt/\n"
"package-lock.json\n"
;

// python template
static const char python_template[] = 
"# Byte-compiled / optimized / DLL files\n"
"__pycache__/\n"
"*.py[cod]\n"
"*$py.class\n"
"\n"
"# C extensions\n"
"*.so\n"
"\n"
"# Distribution / packaging\n"
".Python\n"
"build/\n"
"develop-eggs/\n"
"dist/\n"
"downloads/\n"
"eggs/\n"
".eggs/\n"
"lib/\n"
"lib64/\n"
"parts/\n"
"sdist/\n"
"var/\n"
"wheels/\n"
"*.egg-info/\n"
".installed.cfg\n"
"*.egg\n"
"\n"
"# Virtual environments\n"
"venv/\n"
"env/\n"
"ENV/\n"
".venv\n"
"\n"
"# IDEs\n"
".idea/\n"
".vscode/\n"
"*.swp\n"
"*.swo\n"
"\n"
"# Environment\n"
".env\n"
".env.local\n"
;

// rust template
static const char rust_template[] = 
"# Rust\n"
"target/\n"
"Cargo.lock\n"
"**/*.rs.bk\n"
"*.pdb\n"
;

// vscode template
static const char vscode_template[] = 
"# VS Code\n"
".vscode/\n"
"*.code-workspace\n"
;

// windows template
static const char windows_template[] = 
"# Windows\n"
"Thumbs.db\n"
"ehthumbs.db\n"
"Desktop.ini\n"
;

// All built-in templates
static const builtin_template_t builtin_templates[] = {
    {"c", c_template},
    {"cpp", cpp_template},
    {"go", go_template},
    {"java", java_template},
    {"linux", linux_template},
    {"macos", macos_template},
    {"node", node_template},
    {"python", python_template},
    {"rust", rust_template},
    {"vscode", vscode_template},
    {"windows", windows_template},
    {NULL, NULL}
};

// Get built-in template by name
const char* get_builtin_template(const char *name) {
    for (int i = 0; builtin_templates[i].name != NULL; i++) {
        if (strcasecmp(builtin_templates[i].name, name) == 0) {
            return builtin_templates[i].content;
        }
    }
    return NULL;
}

// Check if template is built-in
int is_builtin_template(const char *name) {
    return get_builtin_template(name) != NULL;
}

// Get all built-in template names
const char** get_builtin_template_names(void) {
    static const char *names[64];
    int count = 0;
    
    for (int i = 0; builtin_templates[i].name != NULL && count < 63; i++) {
        names[count++] = builtin_templates[i].name;
    }
    names[count] = NULL;
    
    return names;
}
